camel:
  component:
    aws-sqs:
      access-key: AKIAV2BPMNGTDZAEV5A4
      secret-key: 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
    aws-sns:
      access-key: AKIAV2BPMNGTDZAEV5A4
      secret-key: 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